### ISSUE TITLE
Uwagi

### ISSUE THREAD

**Issue by MarcinCiura** [Koci0/SpyceInvaders#1]
1. Usunąć katalog `.idea`

2. Mam mieszane uczucia co do używania `pipenv`([*](#Przypisy)). Lepsze jest wrogiem dobrego. Co mam zrobić, jeśli nie mam Pythona 3.7.7? (A nie mam.) Moim zdaniem bardziej przenośne od `Pipfile` jest wpisanie bibliotek zewnętrznych po staremu do `requirements.txt` i instalowanie ich przez `pip install -r requirements.txt`, co zadziała dla dowolnej wersji Pythona 3.x u użytkownika. Gdyby Pan pisał artykuł naukowy, do którego byłby dołączony kod, który ma dawać powtarzalne wyniki, albo puszczał swój program w produkcji przez Dockera, to co innego. Natomiast jeśli ma Pan argumenty na obronę `pipenv` w codziennym życiu, chętnie dam się Panu przekonać.

3. Trochę przerobić `start.py`, żeby `Screen.__init__()` zajmował się konstruowaniem `Screen`, a nie pobocznymi zadaniami:
```python
def main():
    pygame.init()
    game = Game()
    game.run()
    pygame.quit()


if __name__ == '__main__':
    main()
```

4. W Pythonie 3 nie trzeba dziedziczyć z `object`. Czyli wystarczy np. `class Actor` itp.

5. Przydałyby się docstringi do modułów, klas i metod.

6. Sklejanie napisów jest nieładne. Lepiej napisać `f'data/{name}.png'`. Z tej samej beczki: ja bym przekazywał nazwy plików z `.png` na końcu zamiast magicznie doklejać rozszerzenie. Wtedy jeszcze bardziej eleganckie będzie użycie `os.path.join()`.

7. Zamiast `import SpyceInvaders.settings as settings` można napisać `from SpyceInvaders import settings`.

8. Zamiast powtarzających się magicznych napisów, np. `'left'` i `'right'` wprowadzić na górze odpowiedniego modułu albo w `settings.py` stałe `LEFT, RIGHT = range(2)`

9. W `AlienGroup.tick()` zmiena `i` jest niepotrzebna.

10. W `AlienGroup.shoot()` `return None` jest niepotrzebne.

11. Osobiście nie lubię importowania poszczególnych klas/funkcji z modułów, bo to zaśmieca przestrzeń nazw ([punkt 2.2](https://google.github.io/styleguide/pyguide.html#22-imports)).

12. W `Entity.move()` `return False` jest niepotrzebne.

13. Osobiście wolę zamiast `if len(self.alien_group.aliens) == 0` pisać `if not self.alien_group.aliens` ([punkt 2.14.4](https://google.github.io/styleguide/pyguide.html#2144-decision)).

14. W `constants.py`: zwyczajowo piszemy nazwy stałych `W_TEN_SPOSÓB`. Nadto zamiast stałych od `black` do `blue` wolałbym stałe `SURFACE_COLOR`, `BUILDING_COLOR` itp.

### Przypisy
(*) To takie amerykańskie poprawne politycznie wyrażenie, które na polski tłumaczy się "uważam, że to kretyński pomysł".

**Comment by Koci0** [comment]
Dziękuję za uwagi. Odnosząc się do Pańskiej numeracji:

&nbsp;2. Na początku tworzenia projektu, przy konfiguracji środowiska, moduł `pygame==1.9.6` (a więc najnowsza stabilna wersja) nie był kompatybilny z najnowszą wersją Pythona i sytuacja do dzisiaj się nie zmieniła, więc (według mojej wiedzy) nie ma możliwości jednoczesnego korzystania z najnowszej wersji Pythona i stabilnej wersji pygame. Zdecydowałem, że w tym wypadku najłatwiej będzie zastosować osobne środowisko generowane przez `pipenv`. Miałem świadomość, że rozwiązanie może być problematyczne i w późniejszej fazie projektu zamierzałem stworzyć bardziej uniwersalne rozwiązanie. Ma Pan rację co do Pythona 3.7.7, dlatego też zastąpiłem narzędzie `pipenv` przez `pip` i plik `requirements.txt`, jednakże w tym wypadku (dla Pythona > 3.7.7) wymagany jest moduł `pygame==2.0.0.dev6`.

&nbsp;5. Docstringi zostaną dodane w osobnym commit'cie.

**Comment by MarcinCiura** [comment]
Dziękuję (tutaj mam Pythona 3.6.9, a na innej maszynie 3.6.2).
Żeby Pan nie musiał potem przerabiać docstringów, polecam od razu się zastosować do [punktu 3.8](https://google.github.io/styleguide/pyguide.html#38-comments-and-docstrings) (przy czym `Args:`, `Returns/Yields:`, `Raises:` i `Attributes:` może Pan pominąć — nie będę nimi katował studentów).

**Comment by MarcinCiura** [comment]
Projekt wygląda bardzo porządnie. Mam tylko kosmetyczne uwagi.

1. [Tutaj](https://github.com/Koci0/SpyceInvaders/blob/a91882be4179d36bd49a4f9c0c4d6f940885d060/SpyceInvaders/actor.py#L28) i [tutaj](https://github.com/Koci0/SpyceInvaders/blob/a91882be4179d36bd49a4f9c0c4d6f940885d060/SpyceInvaders/entity.py#L14) warto użyć operatora `-=` albo `+=`.
2. [Tutaj](https://github.com/Koci0/SpyceInvaders/blob/a91882be4179d36bd49a4f9c0c4d6f940885d060/SpyceInvaders/alien.py#L22) bardziej elegancko wyglądałoby `self.direction = SWAP_DIRECTION[self.direction]` ze stałym słownikiem `SWAP_DIRECTION` o odpowiedniej zawartości (może być na górze modułu; to wcale nie gorsze miejsce niż w klasie).
3. Jeśli [to](https://github.com/Koci0/SpyceInvaders/blob/a91882be4179d36bd49a4f9c0c4d6f940885d060/SpyceInvaders/entity.py#L21) `True` jest gdzieś używane, to lepsze wrażenie zrobi dopisanie `return False` do pozostałych gałęzi zamiast polegania na domyślnym `return None`. Jeśli zaś nie jest używane, to skasować.
4. [Tutaj](https://github.com/Koci0/SpyceInvaders/blob/a91882be4179d36bd49a4f9c0c4d6f940885d060/SpyceInvaders/screen.py#L50) złamać wiersz w sensownym miejscu. Ponieważ będzie to wewnątrz nawiasów, nie trzeba będzie dodawać `\` na końcu, czego i tak trzeba unikać na rzecz ujmowania łamanych wierszy w nawiasy.
5. Kolory. :) Proszę o nich przeczytać w 3. rozdziale Poradnika.

**Comment by Koci0** [comment]
Zgodnie z uwagami sformatowałem kod oraz dostosowałem go do ogólnych zaleceń, dodałem również testy jednostkowe. Bardzo proszę o informację, czy ma Pan jeszcze jakieś uwagi, jeśli nie, to zamknę ten issue.

**Comment by MarcinCiura** [comment]
LGTM. Gratuluję, jest Pan siedemnasty. W wolnej chwili może Pan [zlikwidować ostatnie (?) znaki `\`](https://github.com/Koci0/SpyceInvaders/blob/807ac84572b8b92108786d4ba2d0968dc42eb659/spyce_invaders/entity.py#L21).

**Comment by Koci0** [comment]
Znaki '\' zostały dodane, ponieważ pełna linia ma 107 znaków, podczas gdy pylint zaleca maksymalną długość 100 znaków. Jednak ma Pan rację, ta różnica jest na tyle mała, że można je zlikwidować.
Dziękuję za wszystkie wskazówki.

**Comment by MarcinCiura** [comment]
Niezupełnie o to mi chodziło. Chodziło mi o otoczenie warunku nawiasami zamiast używania `\` (2. rozdział Poradnika).
